### ISSUE TITLE
Script's main window multiple instances

### ISSUE THREAD

**Issue by Nessus85100** [Ignoble61/script.skinshortcuts#3]
Accidentally the other day i push the button to open script's main window twice and i notice that the window was open twice. Tested again and it turns out that the window is opening so many times how many times the window opens so many times as the times you manage to click before the first instance is open. I manage to do that for 6 times in my testing. Is this a bug or the multiple instances have some purpose ?

Is it ok to post this here or in BigNoid's repo is the proper place ?

Cheers
Nessus

**Comment by Ignoble61** [comment]
This should go on BigNoid's repo :)

**Comment by Nessus85100** [comment]
ok... will do
